# .github/workflows/update-news.yml

name: Scrape Latest News

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- THIS IS THE CORRECTED STEP ---
      - name: Install Firefox & GeckoDriver
        run: |
          # 1. Install Firefox using the package manager, which works correctly.
          sudo apt-get update
          sudo apt-get install -y firefox

          # 2. Manually download, extract, and install GeckoDriver.
          # We specify a stable version to ensure the workflow is consistent.
          GECKODRIVER_VERSION="v0.34.0"
          
          # Download the driver from the official Mozilla release page.
          curl -s -L "https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz" -o geckodriver.tar.gz
          
          # Extract the tarball.
          tar -xvzf geckodriver.tar.gz
          
          # Make the driver executable.
          chmod +x geckodriver
          
          # Move the driver to a directory that is in the system's PATH, so Selenium can find it automatically.
          sudo mv geckodriver /usr/local/bin/

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Scraper
        run: python news_scrape.py

      - name: Commit and Push Updated Files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automated news update"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
