# .github/workflows/update-news.yml

name: Scrape Latest News

# Add a permissions block to allow the workflow to write to the repository.
permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Firefox & GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox geckodriver

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Scraper
        run: python news_scrape.py

      - name: Commit and Push Updated Files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add -A
          
          # Only commit if there are changes to be committed.
          git diff-index --quiet HEAD || git commit -m "Automated news update"
          
          # Use the default GITHUB_TOKEN for the push. No PAT is needed.
          git push
