# .github/workflows/update-news.yml

name: Scrape Latest News

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # SIMPLIFIED STEP: We only need to install GeckoDriver,
      # as Firefox is usually pre-installed on the runners.
      - name: Install GeckoDriver
        run: |
          GECKODRIVER_VERSION="v0.36.0"
          curl -s -L "https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz" -o geckodriver.tar.gz
          tar -xvzf geckodriver.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Scraper
        run: python news_scrape.py

      - name: Commit and Push Updated Files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automated news update"
          git push
